### ISSUE TITLE
Photon styles

### ISSUE THREAD

**Issue by pfrazee** [karissa/dat-explorer#13]
http://photonkit.com/ is a desktop-like styles kit that might work well for this. Yea/nay?

**Comment by okdistribute** [comment]
oh yeah, looks nice!

i also started the lower-level module for the fs rendering here, check it out:  https://github.com/karissa/yo-fs 

it doesn't have any styling so maybe this could go in there.

**Comment by okdistribute** [comment]
I think we're going to just go with what @kriesse decides regarding the app styles but i appreciate the pointer!
