### ISSUE TITLE
signalhub status

### ISSUE THREAD

**Issue by clkao** [karissa/dat-explorer#23]
If you have multiple browser tabs, the connection to signalhub is blocked due to per-host connection limit (hello this is 2016?) and making the UI non-responsive.

There should be an indicator if signalhub is not responsive after a few seconds.

**Comment by juliangruber** [comment]
maybe there's also a way to fix this. could we have random wildcard subdomains with signalhub?

i fear if the ui, ie the whole thread, is blocked, there's no way we can update any ui.

**Comment by mafintosh** [comment]
i'll take a look at this

**Comment by mafintosh** [comment]
@clkao are you sure it is signalhub connections and not webrtc data channels thats the bottleneck here?

**Comment by clkao** [comment]
Aye, Chrome 53.0.2760.0 canary.  From a second tab opening hyperdrive-ui:

![screen shot 2016-06-07 at 6 47 35 pm](https://cloud.githubusercontent.com/assets/69736/15855118/52c617bc-2ce0-11e6-84f4-0a421f35ed88.png)

**Comment by mafintosh** [comment]
signalhub connections are always pending. they are event source streams.

**Comment by clkao** [comment]
This is from the first tab: first 4 connections are done and there are two pending.  I think that's the open connection preventing the second tab from establishing the eventsource.
![screen shot 2016-06-07 at 8 01 40 pm](https://cloud.githubusercontent.com/assets/69736/15856835/b92a6f76-2cea-11e6-8809-523cc77a2e98.png)

Can you reproduce the issue with the second tab in the same browser?

**Comment by okdistribute** [comment]
moving this to datproject/dat.land
