### ISSUE TITLE
back button on browser should trigger back in fs

### ISSUE THREAD

**Issue by berleant** [karissa/dat-explorer#3]
e.g., if you load a dat link (page A), then open a file (page B), then hit back, the browser should display page A again. Currently it's not doing that, at least not on my browser (Chrome, Mac).

**Comment by okdistribute** [comment]
i got the '..' button to work with the most recent commits, but the back button still doesn't work. IIRC, `window.history` might be able to help us. Perhaps there's also a node package for doing this!
