### ISSUE TITLE
restore persistence

### ISSUE THREAD

**Issue by clkao** [karissa/dat-explorer#41]
67952578 switched to memdb.  Are there other concerns that we can't switch back to something persistent?

**Comment by mafintosh** [comment]
no, we should go for persistence again.

**Comment by okdistribute** [comment]
yeah it was just memdb so that it'd be faster for demos

**Comment by mafintosh** [comment]
i've been considering writing a leveldown that writes to memory and in the background flushes to indexeddb in a worker for speeding it up.

**Comment by juliangruber** [comment]
@mafintosh that module would be awesome, and could be called `level-debounce` with an api like

``` js
var db = debounce(level('db'), 1000) // 1000=flush every 1000ms
```

**Comment by mafintosh** [comment]
@juliangruber i like that api.
