### ISSUE TITLE
separate website from lib

### ISSUE THREAD

**Issue by juliangruber** [karissa/dat-explorer#43]
looking at the commit log it's hard to tell what went into the page and what into the lib. can we separate the two?

**Comment by mafintosh** [comment]
👍

**Comment by okdistribute** [comment]
yeah, we can move the code to a dat.land repo since thats where we are deploying it

**Comment by okdistribute** [comment]
im tempted to nix the datland org and just have datproject/dat.land

**Comment by laurengarcia** [comment]
.

**Comment by mafintosh** [comment]
@karissa i think thats a great idea. keep datproject for all the "front facing" projects

**Comment by okdistribute** [comment]
i moved it https://github.com/datproject/dat.land

**Comment by juliangruber** [comment]
> .

@laurengarcia that's a great point :)

**Comment by clkao** [comment]
This seems done already
