### ISSUE TITLE
componentize hyperdrive-ui

### ISSUE THREAD

**Issue by laurengarcia** [karissa/dat-explorer#54]
first pass at this was here:
https://github.com/karissa/hyperdrive-ui/pull/51

improvements to that^^ forthcoming. --lauren

**Comment by laurengarcia** [comment]
second pass: mindux + yo-yo is here:
https://github.com/karissa/hyperdrive-ui/pull/55

**Comment by clkao** [comment]
I think this is moved to https://github.com/datproject/dat.land/pull/104
