### ISSUE TITLE
scrolling on long text files 

### ISSUE THREAD

**Issue by okdistribute** [karissa/dat-explorer#6]
if its a larger file, lets make it scrollable

**Comment by berleant** [comment]
This one is "aargh" material

**Comment by okdistribute** [comment]
yeah super argh. no big deal for now. might just be some css magix

**Comment by berleant** [comment]
But I've been futzing with it since Saturday and if I stop now ...

Sunk cost fallacy, yeah yeah

**Comment by berleant** [comment]
Would this be an acceptable compromise?:

Clicking inside the iFrame can highlight, scroll, etc., but won't clear the display
Clicking anywhere else, outside the iFrame, will clear the display

**Comment by okdistribute** [comment]
oh jeez 

yeah that's fine. or just get rid of the overlay and have a big X on the upper right. it's not an interaction I planned on keeping, feel free to destroy it

**Comment by berleant** [comment]
5c829c074812aa21c06e37290c6861ac47a78164
