### ISSUE TITLE
Viewing files disabled after clicking on any folders

### ISSUE THREAD

**Issue by berleant** [karissa/dat-explorer#8]
To duplicate:
dat hash: 2cc2795f95a23f24fd8f0733dc8d5fe878a9bc2f54d5362ff874341654899dfb
Click Exercises.txt. Works as expected.
Click vocab. Works as expected.
Click a file. No response.
Click the ".." folder. This works as expected.
Click Exercises.txt. It doesn't display any more.

**Comment by okdistribute** [comment]
ahh! we probably need to move the other `browser.on` code into `components/tree-view.js` so every time the browser tree object is created it gets that event set

**Comment by berleant** [comment]
fixed in commit 7dd015f3fb44b8fcb467353af0329f259af4aa0a
