### ISSUE TITLE
random js error that doesn't affect behavior?

### ISSUE THREAD

**Issue by berleant** [karissa/dat-explorer#9]
It pops up when cbs is null.

repro:
load a dat link being hosted using dat-app, look in the js console

![screen shot 2016-01-22 at 12 54 21 pm](https://cloud.githubusercontent.com/assets/1402948/12523086/63fe2a12-c109-11e5-9cc4-c630ade5344e.png)

**Comment by okdistribute** [comment]
rewrote repo for hyperdrive 5+6
